Fix/API Version
Tesorio/adyen-python-api-library pull request #1
Opened 2019-10-23 19:34 UTC by samchristensen

2019-10-23 19:45 UTC, caioariede reviewed
What do you think about this approach, vs being able to pass custom settings?

For example, instead of accessing `settings`, it could access `self.settings`, and then we could set it as:

```python
adyen = Adyen()
adyen.client.settings = custom_settings
```

2019-10-23 19:52 UTC, samchristensen commented
I tried that approach, but I thought it introduced more changes to the code that we wanted. Specifically because it has more side effects than just an optional argument.

the way they currently have their client structured, it defaults to `settings.API_PAYMENT_VERSION`, but in reality if someone was going to make several calls to the API and want to use different versions, they would have to reinstantiate the client every time. 

obviously we don't use a client object more than once currently, but i'm trying to keep it general since others out there might

2019-10-23 19:53 UTC, samchristensen commented
@caioariede I think that approach makes sense if the `def _determine_api_url(...)` function wasn't structured how it is, but since it's structured to fallback to a specific setting value, i think that approach isn't as flexible as we want

2019-10-23 19:58 UTC, caioariede commented
Okay, I still think we should try to see the problem in a higher level. I don't think it makes sense to mix versions for the same service.

One approach I can see, is leveraging settings load so it can be changed to something else, like:

```python
from . import settings
```

to

```python
settings = __import__(os.environ.get("ADYEN_SETTINGS_MODULE", "Adyen.settings"))
```

Thoughts?

2019-10-24 02:06 UTC, samchristensen commented
@caioariede I agree that it doesn't make sense to mix versions, but that's how they are doing it currently. That's what i'm saying, is that I agree that the ideal setup would be to not mix versions and to use something like settings, but they are already mixing versions in their SDK.

For instance, this function will return potentially 3 or 4 different versions, depending on which API you are calling 

https://github.com/Adyen/adyen-python-api-library/blob/278ef674c2ac801a4546c8fbddf9b421f649f032/Adyen/client.py#L96

2019-10-24 13:08 UTC, caioariede commented
@samchristensen when I say about mixing versions, I say about mixing versions for the same service. Having different versions for each service is understandable

2019-10-24 15:50 UTC, samchristensen commented
@caioariede how about instead of doing `import` of the settings, we do something like passing them into the client object? I don't like the idea of having to set and environment variable to override the settings

2019-10-24 15:51 UTC, samchristensen commented
@caioariede I will make the change and see what you think

2019-10-24 17:54 UTC, samchristensen commented
@caioariede the intention with this setup is to allow for us to do the following to override the settings

```
class CustomAdyenClientSettings(AdyenClientSettings):
    API_BIN_LOOKUP_VERSION = 'v50'

....

self.client = AdyenClient(settings=CustomAdyenClientSettings)
```

2019-10-24 17:54 UTC, caioariede commented on Adyen/settings.py
> +class AdyenClientSettings(object):
Are this settings specific to `AdyenClient` or they are used elsewhere?

2019-10-24 17:55 UTC, samchristensen commented on Adyen/settings.py
> +class AdyenClientSettings(object):
at the moment, they only use them here, but i don't want to remove it because i don't want to change too much about their code

2019-10-24 18:00 UTC, caioariede requested changes

2019-10-24 18:00 UTC, caioariede commented on Adyen/settings.py
> +class AdyenClientSettings(object):
I think we shouldn't do any changes in this file

2019-10-24 18:00 UTC, caioariede commented on Adyen/client.py
> +                 http_force=None, live_endpoint_prefix=None, settings=None):
this should be `settings=settings` (keeping the original import)

2019-10-24 18:27 UTC, caioariede requested changes
minor thing

2019-10-24 18:27 UTC, caioariede commented on Adyen/client.py
> +from . import util, settings
should be `settings, util`

2019-10-24 18:32 UTC, caioariede commented
@samchristensen good work! can we change base of this PR to `Adyen/adyen-python-api-library:develop`?

2019-10-24 18:32 UTC, caioariede commented
or you can just close this PR and open a new one pointing to Adyen's repo

2019-10-24 19:47 UTC, closed without merging